# run: conda env create --file environment-dev.yml
name: s2lx
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - scipy
  - gdal
  - libgdal-jp2openjpeg
  - shapely>=2
  - pyproj
  - mercantile
  - geojson
  - scikit-image
  - scikit-learn
  - sphinx
  - flake8
  - pytest
  - black
  - pip
  - pip:
      - isort
      - sphinx-copybutton
      - sphinx_rtd_theme
      - sphinx_mdinclude
