name: Python testing

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Testing
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Miniforge3
          channels: conda-forge
          python-version: 3.9
          activate-environment: s2lx
          auto-activate-base: false
          environment-file: environment-gha.yml
          use-mamba: true

      - name: Lint with flake8
        run: flake8 . --exit-zero --max-complexity=20 --max-line-length=127 --ignore=E501,W503,C901

      - name: Install test
        run: pip install .
